project:
  type: website
  output-dir: docs
  pre-render: "python3 generate_posts_json.py"

lang: en

website:
  title: "Marcellini's Blog"
  favicon: images/banner.jpeg
  site-url: https://en.blogdomarcellini.com.br

  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "ğŸ§­ Explore"
        menu:
          - text: "ğŸ·ï¸ Tags"
            href: tags.qmd
          - text: "ğŸ“‚ Categories"
            href: categories.qmd
      - text: "ğŸ§  Exact Sciences"
        menu:
          - text: "ğŸ§® Mathematics"
            href: posts/mathematics/index.qmd
          - text: "ğŸ“Š Statistics"
            href: posts/statistics/index.qmd
          - text: "ğŸ”­ Physics"
<<<<<<< HEAD
            href: posts/physics/index.qmd
=======
            href: posts/fisica/index.qmd
>>>>>>> 17321b0 (AtualizaÃ§Ãµes no blog)
          - text: "ğŸ’» Programming"
            href: posts/programming/index.qmd
      - text: "ğŸ“ Personal Blog"
        menu:
<<<<<<< HEAD
          - text: "ğŸ“ Personal Posts"
=======
          - text: "ğŸ“ Personal Blog"
>>>>>>> 17321b0 (AtualizaÃ§Ãµes no blog)
            href: posts/personal/index.qmd
          - text: "ğŸ‘¤ About Me and the Blog"
            href: posts/personal/about-the-blog.qmd
      - text: "ğŸ“˜ Courses"
        menu:
          - text: "ğŸ§® Math Courses"
<<<<<<< HEAD
            href: posts/courses/math/index.qmd
          - text: "ğŸ“Š Statistics Courses"
            href: posts/courses/statistics/index.qmd
      - href: guide.qmd
        text: "ğŸ—ºï¸ Site Map"

=======
            href: posts/courses/mathematics/index.qmd
          - text: "ğŸ“Š Statistics Courses"
            href: posts/courses/statistics/index.qmd
      - href: guia.qmd
        text: "ğŸ—ºï¸ Site Map"
>>>>>>> 17321b0 (AtualizaÃ§Ãµes no blog)
    right:
      - text: "PT ğŸ‡§ğŸ‡·"
        href: "https://blogdomarcellini.com.br/"
        target: _blank
        rel: noopener
      - icon: envelope
        text: "Contact"
<<<<<<< HEAD
        href: "mailto:prof.marcellini@gmail.com"
=======
        href: "mailto:prof.marcellini@gmail.com" 
>>>>>>> 17321b0 (AtualizaÃ§Ãµes no blog)

  page-footer:
    left: "Â© 2025 - Marcellini's Blog"
    right: >
<<<<<<< HEAD
      ğŸ“¬ [Contact via Email](mailto:prof.marcellini@gmail.com)<br>
=======
      ğŸ“¬ [Contact via E-mail](mailto:prof.marcellini@gmail.com)<br>
>>>>>>> 17321b0 (AtualizaÃ§Ãµes no blog)
      ğŸ’» <a href="https://github.com/marcellini-celso/blog-marcellini-en.git" target="_blank">GitHub Repository</a>

format:
  html:
    theme: cosmo
    css:
      - styles.css
      - assets/css/custom.css
      - assets/css/cards.css
      - assets/css/chips.css
    toc: true
    toc-title: "On this page"
    highlight-style: github
    open-graph: true
    twitter-card: true
    image: images/banner.png
    include-in-header:
      - "analytics.html"
      - text: |
          <link rel="alternate" hreflang="pt-BR"
                href="https://blogdomarcellini.com.br/" />
          <link rel="alternate" hreflang="x-default"
                href="https://en.blogdomarcellini.com.br/" />
    include-after-body:
      - assets/js/enhance-categories.js

search: true

publish:
  provider: gh-pages
  domain: en.blogdomarcellini.com.br
<<<<<<< HEAD

=======
  
>>>>>>> 17321b0 (AtualizaÃ§Ãµes no blog)
filters:
  - naquiz

resources:
  - robots.txt
  - posts.json
  - images/**

from: markdown+tex_math_dollars+tex_math_single_backslash

