project:
  type: website
  output-dir: docs
  pre-render: "python3 gerar_posts_json.py"

website:
  title: "Marcellini's Blog"
  favicon: images/banner.jpeg
  site-url: https://marcellini-celso.github.io/blog-marcellini-en/

  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "ðŸ·ï¸ Tags ðŸ“‚ Categories"
        menu:
          - text: "ðŸ·ï¸ Tags"
            href: tags.qmd
          - text: "ðŸ“‚ Categories"
            href: categories.qmd
      - text: "ðŸ§  Exact Sciences"
        menu:
          - text: "ðŸ§® Mathematics"
            href: posts/mathematics/index.qmd
          - text: "ðŸ“Š Statistics"
            href: posts/statistics/index.qmd
          - text: "ðŸ”­ Physics"
            href: posts/physics/index.qmd
          - text: "ðŸ’» Programming"
            href: posts/programming/index.qmd
      - text: "ðŸ“ Personal Blog"
        menu:
          - text: "ðŸ“ Personal Posts"
            href: posts/personal/index.qmd
          - text: "ðŸ‘¤ About Me and the Blog"
            href: posts/personal/about-the-blog.qmd
      - text: "ðŸ“˜ Courses"
        menu:
          - text: "ðŸ§® Math Courses"
            href: posts/courses/math/index.qmd
          - text: "ðŸ“Š Statistics Courses"
            href: posts/courses/statistics/index.qmd
      - href: guide.qmd
        text: "ðŸ—ºï¸ Site Map"
    right:
      - icon: envelope
        text: "Contact"
        href: "mailto:prof.marcellini@gmail.com" 

  page-footer:
    left: "Â© 2025 - Marcellini's Blog"
    right: >
      ðŸ“¬ [Contact via Email](mailto:prof.marcellini@gmail.com)<br>
      ðŸ’» <a href="https://github.com/marcellini-celso/blog-marcellini-en.git" target="_blank">GitHub Repository</a>

format:
  html:
    theme: cosmo
    css: 
      - styles.css
      - assets/css/custom.css
    toc: true
    toc-title: "On this page"
    highlight-style: github
    include-in-header: analytics.html

search: true

publish:
  provider: gh-pages

resources:
  - posts.json

